version: '3'
services:
  backend:
    build: ../backend/
    restart: always
    ports:
     - "9000:9000"
  frontend:
    build: ../frontend/
    restart: always
    ports:
     - "3000:3000"
  nginx:
    build: ../nginx/
    ports:
      - 80:80
    volumes:
      - volume-rollplays:/srv/rollplays
networks:
  default:
    external:
      name: network-rollplays
volumes:
  volume-rollplays:
    external: true