version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./backend/
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - VIRTUAL_HOST=~^api\..*
    depends_on:
      - mongodb
    links:
      - mongodb
  frontend:
    build: ./frontend/
    depends_on:
      - backend
    environment:
      - VIRTUAL_HOST=~^(?!api\.).*
  reverseproxy:
    image: jwilder/nginx-proxy
    ports:
     - 80:80
     - 8080:8080
    depends_on:
     - backend
     - frontend
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
