version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./backend/
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    links:
      - mongodb
  frontend:
    build: ./frontend/
    depends_on:
      - backend
