version: '3'
services:
  mongodb:
    restart: always
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=api.rollplays.me
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=rollplays.me
      - REACT_APP_API_URL=http://api.rollplays.me
  reverseproxy:
    restart: always
