version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./backend/
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend