version: "3"
services:
  backend:
    build: ../../backend/
    restart: always
    ports:
      - "9000:9000"
  frontend:
    build: ../../frontend/
    restart: always
    ports:
      - "3000:3000"
  nginx:
    build: ../../nginx/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/rollplays/etc/letsencrypt:/etc/letsencrypt
      - ~/roll-plays/nginx-letsencrypt/site:/data/letsencrypt
networks:
  default:
    external:
      name: network-rollplays
