const EVENT_TYPES = {
    DELETE_CONTENT: "DELETE_CONTENT",
    DELETE_CONTENT_BACKWARD: "DELETE_CONTENT_BACKWARD",
    DELETE_CONTENT_FORWARD: "DELETE_CONTENT_FORWARD",
    ARROW_LEFT: "ARROW_LEFT",
    ARROW_RIGHT: "ARROW_RIGHT",
    INSERT_TEXT: "INSERT_TEXT",
    INSERT_PARAGRAPH: "INSERT_PARAGRAPH"
};

export default EVENT_TYPES;
